import {regionKey,polygonValid} from '/api/artifact?path=algorithms/3d_char_details/gui/uv-regions.js';
import {drawField,sampleField,pickUV} from '/api/artifact?path=algorithms/3d_char_details/gui/influence-view.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function uvEditor(root,{read,change,field:readField,preview,signal}){
 const host=document.createElement('section');host.className='char-uv-panel';host.hidden=true;
 host.innerHTML=`<header><div><small>2D UV / LINKED 3D</small><h3 data-title></h3></div><button data-close aria-label="Close influence editor">×</button></header>
 <p data-error role="alert" hidden></p>
 <label data-owner-row hidden>Side <select data-owner aria-label="Garment region side"></select></label><label>Surface <select data-sheet aria-label="UV surface"></select></label>
 <div class="char-field-view"><label>Show <select data-layer aria-label="Influence display"><option value="result">Resulting movement</option><option value="native">Authored movement</option><option value="weights">Editable influence</option></select></label><details class="char-view-options"><summary>View options</summary><label><input type="checkbox" data-colors checked> Surface colors</label><label><input type="checkbox" data-wire> UV edges</label><label><input type="checkbox" data-preview checked> Linked 3D colors</label>
 <label>Overlay <input type="range" data-opacity min="0" max="1" step=".05" value=".35" aria-label="Influence overlay opacity"></label></details></div>
 <div class="char-uv-map"><canvas width="512" height="512" aria-label="Unwrapped surface colors and influence"></canvas><svg viewBox="0 0 512 512" aria-label="UV influence editing surface"></svg></div>
 <div class="char-field-legend"><span>0</span><i></i><span>0.5</span><i></i><span>1</span></div>
 <div class="char-presets"><button data-fit>Fit UVs</button><button data-focus>Frame affected area</button><button data-tool="inspect" aria-pressed="true">Inspect</button><button data-tool="polygon" aria-pressed="false">Polygon</button><button data-tool="brush" aria-pressed="false">Brush</button><button data-tool="vertex" aria-pressed="false">Vertex</button></div>
 <p data-sample role="status">Click a UV vertex or the 3D surface to inspect its influence.</p>
 <div class="char-field-edit"><label>Influence <input type="number" min="0" max="1" step=".05" value=".6" data-value aria-label="Edit influence value"></label><label>Soft edge / brush radius <input type="range" min=".005" max=".25" step=".005" value=".04" data-radius aria-label="Influence falloff radius"><output>.040</output></label></div>
 <label><input type="checkbox" data-enabled checked> Apply influence edits</label>
 <div data-polygon-tools hidden><label>Polygon <select data-polygon aria-label="Saved influence polygon"></select></label><div class="char-presets"><button data-new>New polygon</button><button data-finish disabled>Finish polygon</button></div><div class="char-uv-point"><label>Point <select data-point aria-label="Polygon point"></select></label><label>U <input type="number" min="0" max="1" step=".001" data-u aria-label="Point U"></label><label>V <input type="number" min="0" max="1" step=".001" data-v aria-label="Point V"></label></div><div class="char-presets"><button data-add>Add midpoint</button><button data-remove>Remove point</button><button data-delete-polygon>Delete polygon</button></div></div>
 <div class="char-presets"><button data-undo>Undo last stroke / polygon</button><button data-reset>Restore authored field</button></div>
 <p class="char-hint" data-note></p><details class="char-uv-help"><summary>What these values mean</summary><p>The color surface is baked from this model’s material and vertex colors. Body and face use a separate unwrapped editing atlas; clothing keeps its original UVs. Wheel to zoom; right-drag to pan. Click the 3D model to locate the same triangle here.</p><p>Authored movement is the length of each vertex’s original deformation vector, divided by the field’s peak. Editable influence multiplies that vector: 1 keeps it, 0.6 keeps 60%, 0 removes it. Resulting movement combines both. These are deformation influences, not skeleton skin weights. The property slider still controls the signed amount.</p><p>Brush edges blend continuously. Polygon interiors use the selected value, fading into the existing field outside. Vertices duplicated at UV seams share the same influence. Clothing attachment constraints run afterward.</p></details>`;
 root.querySelector('.char-viewport').append(host);
 const q=s=>host.querySelector(s),canvas=q('canvas'),ctx=canvas.getContext('2d'),svg=q('svg'),buffer=document.createElement('canvas');buffer.width=buffer.height=512;
 let part,control,label,region,field,sheet,tool='inspect',selected=-1,point=0,draft=null,drag=null,panDrag=null,painting=false,lastDab=null,marker=null,pending=0,zoom=1,pan=[0,0],history=[];
 const clamp=x=>Math.max(0,Math.min(1,x)),polygon=()=>selected>=0?region.edits?.[selected]:null,value=()=>clamp(Number(q('[data-value]').value)||0),radius=()=>Number(q('[data-radius]').value);
 const options=()=>({layer:q('[data-layer]').value,opacity:Number(q('[data-opacity]').value),colors:q('[data-colors]').checked,wire:q('[data-wire]').checked});
 function remember(){history.push(structuredClone(region));if(history.length>40)history.shift();}
 function commit(){if(part==='surface'&&region.edits?.length)region.atlasHash=field.atlasHash;try{change(regionKey(part,control),structuredClone(region));loadField();}catch(error){region=structuredClone(read()[regionKey(part,control)]||{enabled:true,edits:[]});region.edits??=[];selected=-1;draft=null;loadField();q('[data-sample]').textContent=error.message;}}
 function schedule(){if(pending)return;pending=requestAnimationFrame(()=>{pending=0;commit();});}
 function flush(){if(pending){cancelAnimationFrame(pending);pending=0;commit();}}
 function loadField(){q('[data-title]').textContent=label;host.classList.remove('char-uv-failed');q('[data-error]').hidden=true;
  try{field=readField(part,control);const sheets=new Map(field.entries.filter(e=>e.atlas).map(e=>[e.atlas.sheet,e.atlas.label]));if(!sheets.size)throw new Error('No editable UV surface is available for this adjustment.');if(!sheets.has(sheet))sheet=field.entries.filter(e=>e.atlas).sort((a,b)=>b.native.reduce((s,v)=>s+v,0)-a.native.reduce((s,v)=>s+v,0))[0]?.atlas.sheet;
  q('[data-sheet]').innerHTML=[...sheets].map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');q('[data-sheet]').value=sheet;
  q('[data-title]').textContent=label;q('[data-enabled]').checked=region.enabled;
  q('[data-note]').textContent=`${part==='surface'?'Unwrapped editing atlas':'Original garment UVs'} · authored peak ${(field.peak*1000).toFixed(2)} mm per unit adjustment. ${region.points?'Existing projection/UV mask is retained in the result. ':''}${region.edits?.length||0} influence edits.`;
  raster();if(marker)inspect(marker.u,marker.v);return true;
  }catch(error){field=null;preview.clear();host.classList.add('char-uv-failed');q('[data-error]').hidden=false;q('[data-error]').textContent=`Could not display this influence field: ${error.message} Close this panel and reopen the adjustment to retry.`;return false;}
 }
 function raster(){drawField(buffer,field,sheet,options());if(q('[data-preview]').checked)preview.show(field,options().layer,options().opacity);else preview.clear();draw();}
 function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#26373f';ctx.fillRect(0,0,512,512);ctx.setTransform(zoom,0,0,zoom,...pan);ctx.drawImage(buffer,0,0);ctx.setTransform(1,0,0,1,0,0);
  const current=draft||polygon()?.points,points=current||[],closed=!draft,polygons=(region.edits||[]).map((e,i)=>e.type==='polygon'&&e.sheet===sheet?`<polygon points="${e.points.map(([u,v])=>`${u*512},${(1-v)*512}`).join(' ')}" fill="none" stroke="${i===selected?'#ffd48b':'#fff6'}" stroke-width="${2/zoom}"/>`:'').join('');
  svg.innerHTML=`<g transform="translate(${pan}) scale(${zoom})">${polygons}${draft?`<polyline points="${points.map(([u,v])=>`${u*512},${(1-v)*512}`).join(' ')}" fill="none" stroke="#ffd48b" stroke-width="${2/zoom}"/>`:''}${tool==='polygon'?points.map(([u,v],i)=>`<circle data-handle="${i}" cx="${u*512}" cy="${(1-v)*512}" r="${(i===point?13:10)/zoom}" fill="#ffe0a4" stroke="#172c36" stroke-width="${1/zoom}" tabindex="0" role="button" aria-label="Region point ${i+1}"/>`).join(''):''}${marker?`<circle cx="${marker.u*512}" cy="${(1-marker.v)*512}" r="${6/zoom}" fill="none" stroke="white" stroke-width="${2/zoom}"/>`:''}</g>`;
  q('[data-polygon-tools]').hidden=tool!=='polygon';q('[data-finish]').disabled=!draft||!polygonValid(draft);q('[data-undo]').disabled=!history.length;
  q('[data-polygon]').innerHTML='<option value="-1">Choose or draw a polygon</option>'+(region.edits||[]).map((e,i)=>e.type==='polygon'&&e.sheet===sheet?`<option value="${i}">Polygon ${i+1} · ${e.value.toFixed(2)}</option>`:'').join('');q('[data-polygon]').value=selected;
  q('[data-point]').innerHTML=points.map((_,i)=>`<option value="${i}">P${i+1}</option>`).join('');point=Math.min(point,Math.max(0,points.length-1));q('[data-point]').value=point;
  for(const [selector,axis]of [['[data-u]',0],['[data-v]',1]]){const input=q(selector);input.disabled=!points.length;if(document.activeElement!==input)input.value=points[point]?.[axis]?.toFixed(3)||'';}
  q('[data-add]').disabled=!points.length||points.length>=32;q('[data-remove]').disabled=points.length<=3;q('[data-delete-polygon]').disabled=selected<0;
 }
 function inspect(u,v){marker={u,v};const s=sampleField(field,sheet,u,v);if(s)preview.select(s.mesh,s.vertex);q('[data-sample]').textContent=s?`Nearest vertex ${s.vertex} · authored ${s.native.toFixed(3)} × influence ${s.weight.toFixed(3)} = ${(s.native*s.weight).toFixed(3)} · native ${(s.movement*1000).toFixed(2)} mm`:'No vertex on this surface';draw();return s;}
 function coordinate(e){const r=svg.getBoundingClientRect();return [clamp(((e.clientX-r.left)/r.width*512-pan[0])/zoom/512),clamp(1-((e.clientY-r.top)/r.height*512-pan[1])/zoom/512)];}
 function selectPolygon(i){selected=i;point=0;draft=null;const p=polygon();if(p){q('[data-value]').value=p.value;q('[data-radius]').value=p.feather||.005;q('output').value=(p.feather||0).toFixed(3);}draw();}
 function setTool(t){tool=t;root.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));if(t==='polygon'&&selected<0)draft=[];else if(t!=='polygon')draft=null;draw();}
 function editPoint(p){const points=draft||polygon()?.points;if(!points)return;const next=points.map(x=>[...x]);next[point]=p;if(!draft&&!polygonValid(next)){q('[data-sample]').textContent='Edges cannot cross or collapse.';return;}if(draft)draft=next;else{polygon().points=next;region.enabled=true;schedule();}draw();}
 function activateEdit(){if(!region.enabled&&!region.edits.length){delete region.points;delete region.projection;delete region.feather;}region.enabled=true;}
 function dab(p,exact=false){if(region.edits.length>=2048){q('[data-sample]').textContent='Edit limit reached; undo or restore this field before adding more.';return;}if(!exact&&lastDab&&Math.hypot(p[0]-lastDab[0],p[1]-lastDab[1])<radius()*.25)return;
  activateEdit();region.edits.push({type:'brush',sheet,center:p,radius:exact?.000001:radius(),value:value(),opacity:1});region.enabled=true;lastDab=p;marker={u:p[0],v:p[1]};schedule();
 }
 svg.addEventListener('contextmenu',e=>e.preventDefault(),{signal});
 svg.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*512,y=(e.clientY-r.top)/r.height*512,next=Math.max(1,Math.min(12,zoom*Math.exp(-e.deltaY*.002)));pan=[x-(x-pan[0])*next/zoom,y-(y-pan[1])*next/zoom];zoom=next;draw();},{signal,passive:false});
 svg.addEventListener('pointerdown',e=>{e.preventDefault();svg.setPointerCapture(e.pointerId);if(e.button===1||e.button===2){panDrag={x:e.clientX,y:e.clientY,pan:[...pan]};return;}const p=coordinate(e),handle=e.target.getAttribute('data-handle');if(handle!==null){point=Number(handle);drag=e.pointerId;remember();draw();return;}
  if(tool==='inspect'){inspect(...p);return;}if(tool==='polygon'){if(!draft)draft=[];if(draft.length<32)draft.push(p);draw();return;}
  remember();if(tool==='vertex'){const s=inspect(...p);if(s&&s.distance<.04/zoom)dab([s.u,s.v],true);return;}painting=true;lastDab=null;dab(p);
 },{signal});
 svg.addEventListener('pointermove',e=>{if(panDrag){const r=svg.getBoundingClientRect();pan=[panDrag.pan[0]+(e.clientX-panDrag.x)*512/r.width,panDrag.pan[1]+(e.clientY-panDrag.y)*512/r.height];draw();}else if(drag===e.pointerId)editPoint(coordinate(e));else if(painting)dab(coordinate(e));},{signal});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])svg.addEventListener(event,()=>{drag=null;panDrag=null;painting=false;lastDab=null;},{signal});
 svg.addEventListener('keydown',e=>{const h=e.target.getAttribute('data-handle');if(h===null||!e.key.startsWith('Arrow'))return;e.preventDefault();point=Number(h);const p=[...(draft||polygon().points)[point]],step=e.shiftKey?.001:.01;remember();p[0]=clamp(p[0]+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0));p[1]=clamp(p[1]+(e.key==='ArrowUp'?step:e.key==='ArrowDown'?-step:0));editPoint(p);svg.querySelector(`[data-handle="${point}"]`)?.focus();},{signal});
 host.addEventListener('input',e=>{if(e.target.matches('[data-opacity]'))raster();if(e.target.matches('[data-radius],[data-value]')){q('output').value=radius().toFixed(3);if(tool==='polygon'&&polygon()){polygon().value=value();polygon().feather=radius();region.enabled=true;schedule();}}
  if(e.target.matches('[data-u],[data-v]')&&e.target.value!==''&&e.target.validity.valid)editPoint([clamp(Number(q('[data-u]').value)),clamp(Number(q('[data-v]').value))]);
 },{signal});
 host.addEventListener('change',e=>{if(e.target.matches('[data-owner]')){flush();part=e.target.value;region=structuredClone(read()[regionKey(part,control)]||{enabled:true,edits:[]});region.edits??=[];history=[];selected=-1;draft=null;sheet=null;loadField();}if(e.target.matches('[data-sheet]')){sheet=e.target.value;selected=-1;draft=null;marker=null;zoom=1;pan=[0,0];raster();}if(e.target.matches('[data-layer],[data-colors],[data-wire],[data-preview]'))raster();if(e.target.matches('[data-enabled]')){remember();region.enabled=e.target.checked;schedule();}if(e.target.matches('[data-polygon]'))selectPolygon(Number(e.target.value));if(e.target.matches('[data-point]')){point=Number(e.target.value);draw();}},{signal});
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))close();if(b.dataset.tool)setTool(b.dataset.tool);
  if(b.hasAttribute('data-new')){selected=-1;draft=[];point=0;draw();}
  if(b.hasAttribute('data-finish')&&draft&&polygonValid(draft)){remember();activateEdit();region.edits.push({type:'polygon',sheet,points:draft,feather:radius(),value:value(),opacity:1});selected=region.edits.length-1;draft=null;region.enabled=true;schedule();draw();}
  if(b.hasAttribute('data-add')){const p=draft||polygon()?.points;if(p&&p.length<32){remember();const a=p[point],b=p[(point+1)%p.length];p.splice(++point,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);if(!draft)schedule();draw();}}
  if(b.hasAttribute('data-remove')){const p=draft||polygon()?.points;if(p?.length>3){const next=p.filter((_,i)=>i!==point);if(draft||polygonValid(next)){remember();if(draft)draft=next;else{polygon().points=next;schedule();}point=0;draw();}}}
  if(b.hasAttribute('data-delete-polygon')&&selected>=0){remember();region.edits.splice(selected,1);selected=-1;draft=null;schedule();}
  if(b.hasAttribute('data-undo')&&history.length){flush();region=history.pop();selected=-1;draft=null;commit();}
  if(b.hasAttribute('data-reset')){remember();region={enabled:true,edits:[]};selected=-1;draft=null;schedule();}
  if(b.hasAttribute('data-fit')){zoom=1;pan=[0,0];draw();}
  if(b.hasAttribute('data-focus')){let lo=[1,1],hi=[0,0];for(const e of field.entries){if(e.atlas.sheet!==sheet)continue;const uv=e.atlas.uv,idx=e.mesh.geometry.index;for(let c=0;c<uv.length/2;c++){const i=idx?idx.getX(c):c;if(e.native[i]<field.peak*.025||(part==='surface'&&uv[c*2]>.975))continue;lo=[Math.min(lo[0],uv[c*2]),Math.min(lo[1],uv[c*2+1])];hi=[Math.max(hi[0],uv[c*2]),Math.max(hi[1],uv[c*2+1])];}}zoom=Math.max(1,Math.min(12,.85/Math.max(hi[0]-lo[0],hi[1]-lo[1],.01)));pan=[256-(lo[0]+hi[0])*256*zoom,256-(1-(lo[1]+hi[1])/2)*512*zoom];draw();}
 },{signal});
 function close(){flush();host.hidden=true;host.parentElement.classList.remove('char-influence-open');preview.clear();}
 signal.addEventListener('abort',()=>{cancelAnimationFrame(pending);preview.dispose();host.parentElement.classList.remove('char-influence-open');host.remove();},{once:true});
 return {flush,close,refresh(){if(!host.hidden){flush();region=structuredClone(read()[regionKey(part,control)]||{enabled:true,edits:[]});region.edits??=[];if(selected>=region.edits.length)selected=-1;loadField();}},pick(name,uv,hit){if(host.hidden)return false;if(!field)return true;const p=pickUV(field,hit);if(!p)return true;sheet=p.sheet;selected=-1;draft=null;zoom=4;pan=[256-p.u*512*zoom,256-(1-p.v)*512*zoom];loadField();inspect(p.u,p.v);return true;},open(p,n,title,sides=[p]){flush();q('[data-owner-row]').hidden=p==='surface'||sides.length<2;q('[data-owner]').innerHTML=sides.map(s=>`<option value="${esc(s)}">${esc(s.replaceAll('_',' '))}</option>`).join('');q('[data-owner]').value=p;part=p;control=n;label=title;region=structuredClone(read()[regionKey(part,control)]||{enabled:true,edits:[]});region.edits??=[];history=[];selected=-1;draft=null;marker=null;zoom=1;pan=[0,0];sheet=null;host.hidden=false;host.parentElement.classList.add('char-influence-open');if(loadField()){selectPolygon(region.edits.findLastIndex(e=>e.type==='polygon'&&e.sheet===sheet));setTool('inspect');}q('[data-close]').focus();}};
}
